.PHONY: clean All

All:
	@echo "----------Building project:[ e_n - Debug ]----------"
	@cd "e_n" && "$(MAKE)" -f  "e_n.mk"
clean:
	@echo "----------Cleaning project:[ e_n - Debug ]----------"
	@cd "e_n" && "$(MAKE)" -f  "e_n.mk" clean
