.PHONY: clean All

All:
	@echo "----------Building project:[ fun_prototypes - Debug ]----------"
	@cd "func1" && "$(MAKE)" -f  "fun_prototypes.mk"
clean:
	@echo "----------Cleaning project:[ fun_prototypes - Debug ]----------"
	@cd "func1" && "$(MAKE)" -f  "fun_prototypes.mk" clean
